import Head from 'next/head';
// import Image from 'next/image';
import Header from '../src/components/UI/Header';
import Nav from '../src/components/UI/Nav';
import Results from '../src/components/main/Results';
import requests from '../src/utils/requests';
import React, { useEffect, useState } from 'react';
import { GetServerSideProps, NextPage } from 'next';
import { TrendingTypes } from '../types/mainTypings';

interface Props {
  results: TrendingTypes;
}

const Home: NextPage<Props> = ({ results }) => {
  return (
    <div>
      <Head>
        <title>Movie Rating timdb</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <Nav />

      <Results results={results.results} />
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { genre } = context.query;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request,
    },
  };
};
