import Head from 'next/head';
// import Image from 'next/image';
import Header from '../components/UI/Header';
import Nav from '../components/UI/Nav';
import Results from '../components/main/Results';
import requests from '../utils/requests';
import { useEffect, useState } from 'react';

const Home = ({ results }) => {
  const [media, setMedia] = useState({
    media: {
      most: {},
      video: {},
      backdrops: {},
      posters: {},
      recs: {},
    },
    title: 'most',
  });
  const video = [
    { id: 1, id2: 2, id3: 3 },
    { id: 4, id2: 5, id3: 6 },
    ,
    { id: 7, id2: 8, id3: 9 },
  ];
  useEffect(() => {
    setMedia((prevState) => ({
      ...prevState,
      media: {
        ...prevState.media,
        video,
      },
    }));
  }, []);

  return (
    <div>
      <Head>
        <title>Movie Rating timdb</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <Nav />

      <Results results={results} />
    </div>
  );
};

export default Home;

export async function getServerSideProps(context) {
  const { genre } = context.query;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request,
    },
  };
}
